In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn')

In [4]:
import yfinance as yf

In [9]:
from niftystockslist import niftylist

In [27]:
list = niftylist('Nifty500')
list[:] = [word.strip() + ".NS" for word in list]

In [26]:
data = yf.download(list, start="2022-03-01", end="2022-03-20", interval= '15m')

[*********************100%***********************]  501 of 501 completed

2 Failed downloads:
- BURGERKING.NS: No data found for this date range, symbol may be delisted
- PHILIPCARB.NS: No data found, symbol may be delisted

In [28]:
data['Close']

,3MINDIA.NS,AARTIDRUGS.NS,AARTIIND.NS,AAVAS.NS,ABB.NS,ABBOTINDIA.NS,ABCAPITAL.NS,ABFRL.NS,ACC.NS,ADANIENT.NS,...,WELCORP.NS,WELSPUNIND.NS,WESTLIFE.NS,WHIRLPOOL.NS,WIPRO.NS,WOCKPHARMA.NS,YESBANK.NS,ZEEL.NS,ZENSARTECH.NS,ZYDUSWELL.NS
Datetime,,,,,,,,,,,,,,,,,,,,,
2022-03-02 09:15:00+05:30,21320.000000,461.700012,922.950012,2837.350098,2181.949951,17388.300781,105.550003,270.250000,2097.350098,1659.349976,...,146.600006,106.550003,456.549988,1667.500000,558.000000,342.500000,13.20,235.550003,352.549988,1596.599976
2022-03-02 09:30:00+05:30,21248.400391,458.000000,920.650024,2825.000000,2173.100098,17250.000000,104.750000,267.899994,2088.350098,1656.699951,...,146.649994,106.349998,454.350006,1657.150024,553.849976,341.549988,13.10,236.149994,350.000000,1587.800049
2022-03-02 09:45:00+05:30,21152.349609,458.200012,917.849976,2825.000000,2174.000000,17232.699219,104.400002,267.549988,2085.399902,1653.349976,...,150.750000,106.199997,452.100006,1662.949951,552.299988,340.450012,13.10,236.399994,349.299988,1592.199951
2022-03-02 10:00:00+05:30,21160.050781,458.250000,918.900024,2835.000000,2182.050049,17123.199219,104.199997,268.149994,2069.449951,1659.500000,...,149.949997,106.449997,453.299988,1694.900024,553.599976,341.100006,13.15,234.550003,351.250000,1589.800049
2022-03-02 10:15:00+05:30,21160.000000,457.899994,916.599976,2829.350098,2174.300049,17199.750000,104.050003,267.799988,2069.000000,1655.050049,...,150.300003,106.500000,453.100006,1670.000000,552.549988,341.000000,13.10,236.850006,349.500000,1582.900024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-17 14:30:00+05:30,20139.900391,457.350006,895.900024,2431.050049,2117.949951,17176.050781,108.949997,287.549988,2129.550049,1813.150024,...,144.550003,102.099998,472.750000,1656.599976,605.900024,291.600006,12.75,260.600006,378.799988,1525.599976
2022-03-17 14:45:00+05:30,20165.449219,456.000000,895.200012,2450.449951,2125.000000,17187.000000,110.199997,286.049988,2122.149902,1820.050049,...,144.000000,102.300003,474.450012,1649.849976,603.250000,291.649994,12.80,260.250000,377.500000,1529.800049
2022-03-17 15:00:00+05:30,20137.099609,455.350006,890.500000,2501.449951,2108.350098,17289.000000,109.849998,285.450012,2118.850098,1821.000000,...,144.000000,102.000000,465.049988,1645.199951,599.650024,292.100006,13.20,259.450012,377.299988,1504.500000
2022-03-17 15:15:00+05:30,19984.250000,455.649994,892.000000,2500.050049,2093.500000,17257.900391,109.849998,285.250000,2121.850098,1820.000000,...,143.899994,102.300003,461.950012,1652.000000,602.799988,292.250000,13.10,258.799988,376.450012,1498.949951
2022-03-17 15:30:00+05:30,NaN,454.850006,891.599976,2489.850098,2101.350098,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,463.049988,1646.000000,NaN,NaN,12.95,NaN,NaN,NaN